'use client';

import { useState, useRef, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import ConnectionStatus from '@/components/ConnectionStatus';
import { startInterview, MAX_QUESTIONS } from '@/lib/api';
import type { StartResponse } from '@/types/index';

/* ── Static data ──────────────────────────────────────────────────────────── */
const PREVIEW_METRICS = [
  { label: 'Confidence',     pct: 82, color: '#3D7EFF' },
  { label: 'Knowledge',      pct: 91, color: '#22D3A0' },
  { label: 'Fluency',        pct: 76, color: '#A78BFA' },
  { label: 'Skill Relevance',pct: 88, color: '#60EFFF' },
];

const FEATURES = [
  { icon: '◈', text: 'Resume-tailored questions generated by AI' },
  { icon: '◈', text: 'Real-time scoring across 5 performance metrics' },
  { icon: '◈', text: 'Full ATS compatibility report after every session' },
];

const STATS = [
  { num: MAX_QUESTIONS, label: 'Questions' },
  { num: 5,            label: 'Metrics'   },
  { num: 100,          label: 'ATS Score' },
];

/* ── Component ────────────────────────────────────────────────────────────── */
export default function HomePage() {
  const router = useRouter();
  const inputRef = useRef<HTMLInputElement>(null);

  const [file,    setFile]    = useState<File | null>(null);
  const [drag,    setDrag]    = useState(false);
  const [loading, setLoading] = useState(false);
  const [error,   setError]   = useState('');

  /* file validation */
  function acceptFile(f: File) {
    if (!f.name.match(/\.(pdf|txt)$/i)) {
      setError('Please upload a PDF or TXT resume file.');
      return;
    }
    setError('');
    setFile(f);
  }

  const onDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDrag(false);
    const f = e.dataTransfer.files[0];
    if (f) acceptFile(f);
  }, []);

  /* start interview */
  async function handleStart() {
    if (!file) { setError('Please select your resume first.'); return; }
    setLoading(true);
    setError('');
    try {
      const data: StartResponse = await startInterview(file);
      localStorage.setItem('ait_session', JSON.stringify(data));
      router.push('/interview');
    } catch (err: unknown) {
      setError(
        err instanceof Error
          ? err.message
          : 'Failed to start. Make sure your FastAPI backend is running.',
      );
    } finally {
      setLoading(false);
    }
  }

  /* ── Render ─────────────────────────────────────────────────────────────── */
  return (
    <div className="min-h-screen bg-ink-950 relative overflow-hidden">

      {/* ── Ambient orbs ── */}
      <div className="orb w-96 h-96" style={{ background:'rgba(61,126,255,0.18)', top:'-100px', left:'-80px', animationDuration:'14s' }} />
      <div className="orb w-72 h-72" style={{ background:'rgba(96,239,255,0.08)', top:'35%', right:'-60px', animationDuration:'19s', animationDelay:'-6s' }} />
      <div className="orb w-64 h-64" style={{ background:'rgba(167,139,250,0.1)', bottom:'-60px', left:'30%', animationDuration:'22s', animationDelay:'-11s' }} />

      {/* ── Grid texture ── */}
      <div className="grid-texture" />

      {/* ── Navbar ── */}
      <nav className="relative z-20 border-b border-white/[0.05] bg-ink-950/80 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          {/* Brand */}
          <div className="flex items-center gap-3">
            <div
              className="w-8 h-8 rounded-lg flex items-center justify-center shadow-glow-sm"
              style={{ background: 'linear-gradient(135deg,#3D7EFF,#60EFFF)' }}
            >
              <span className="font-display font-bold text-xs text-white">IP</span>
            </div>
            <span className="font-display font-bold text-white text-lg tracking-tight">
              Interview<span className="azure-text">Pro</span>
            </span>
          </div>

          <ConnectionStatus />
        </div>
      </nav>

      {/* ── Main content ── */}
      <div className="relative z-10 max-w-7xl mx-auto px-6 py-20">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">

          {/* ── LEFT: hero copy + preview ── */}
          <div className="animate-slideIn">
            {/* Pill badge */}
            <div
              className="inline-flex items-center gap-2 mb-8 px-3 py-1.5 rounded-full border border-azure/30"
              style={{ background: 'rgba(61,126,255,0.08)' }}
            >
              <span className="w-1.5 h-1.5 rounded-full bg-azure animate-pulse" />
              <span className="text-azure text-xs font-medium font-mono tracking-widest uppercase">
                AI-Powered Interview Coach
              </span>
            </div>

            {/* Headline */}
            <h1 className="font-display text-5xl font-bold leading-[1.1] text-white mb-6">
              Prepare smarter.<br />
              <span className="azure-text">Land the role.</span>
            </h1>

            <p className="text-white/50 text-lg leading-relaxed mb-10 max-w-md">
              Upload your resume. Answer {MAX_QUESTIONS} questions tailored to your
              experience. Get a deep-dive performance report with real scores.
            </p>

            {/* Metric preview card */}
            <div className="glass-card p-5 max-w-sm">
              <p className="text-xs text-white/25 font-mono uppercase tracking-widest mb-4">
                Sample performance metrics
              </p>
              {PREVIEW_METRICS.map((m) => (
                <div key={m.label} className="mb-3 last:mb-0">
                  <div className="flex justify-between mb-1.5">
                    <span className="text-xs text-white/45">{m.label}</span>
                    <span className="text-xs font-mono font-medium" style={{ color: m.color }}>{m.pct}%</span>
                  </div>
                  <div className="h-1 rounded-full overflow-hidden" style={{ background: 'rgba(255,255,255,0.06)' }}>
                    <div
                      className="h-full rounded-full metric-fill"
                      style={{
                        width:      `${m.pct}%`,
                        background: `linear-gradient(90deg,${m.color}99,${m.color})`,
                        boxShadow:  `0 0 6px ${m.color}70`,
                      }}
                    />
                  </div>
                </div>
              ))}
            </div>

            {/* Stats */}
            <div className="flex items-center gap-10 mt-10">
              {STATS.map((s) => (
                <div key={s.label}>
                  <p className="font-display font-bold text-3xl text-white">{s.num}</p>
                  <p className="text-white/28 text-sm mt-0.5">{s.label}</p>
                </div>
              ))}
            </div>
          </div>

          {/* ── RIGHT: upload card ── */}
          <div className="animate-slideIn" style={{ animationDelay: '0.12s', opacity: 0 }}>
            <div className="glass-card p-8 relative overflow-hidden">
              {/* Inner glow */}
              <div
                className="absolute -top-24 -right-24 w-64 h-64 rounded-full pointer-events-none"
                style={{ background: 'rgba(61,126,255,0.08)', filter: 'blur(60px)' }}
              />

              <div className="relative z-10">
                <h2 className="font-display font-bold text-xl text-white mb-1">Start your session</h2>
                <p className="text-white/38 text-sm mb-8">
                  Upload your resume to generate personalised questions
                </p>

                {/* ── Drop zone ── */}
                <div
                  className={`drop-zone border-2 border-dashed rounded-2xl p-10 text-center cursor-pointer mb-6 ${
                    drag ? 'drag-active border-azure/60' : 'border-white/10 hover:border-azure/40'
                  } ${file ? 'file-ok' : ''}`}
                  onClick={() => inputRef.current?.click()}
                  onDrop={onDrop}
                  onDragOver={(e) => { e.preventDefault(); setDrag(true); }}
                  onDragLeave={() => setDrag(false)}
                >
                  <input
                    ref={inputRef}
                    type="file"
                    accept=".pdf,.txt"
                    className="hidden"
                    onChange={(e) => { const f = e.target.files?.[0]; if (f) acceptFile(f); }}
                  />

                  {file ? (
                    <>
                      <div className="w-12 h-12 rounded-xl border flex items-center justify-center mx-auto mb-3"
                        style={{ background: 'rgba(34,211,160,0.12)', borderColor: 'rgba(34,211,160,0.25)' }}>
                        <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
                          <circle cx="10" cy="10" r="9" stroke="#22D3A0" strokeWidth="1.5"/>
                          <path d="M6 10l3 3 5-5" stroke="#22D3A0" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                        </svg>
                      </div>
                      <p className="font-medium text-sm" style={{ color: '#22D3A0' }}>{file.name}</p>
                      <p className="text-white/28 text-xs mt-1">
                        {(file.size / 1024).toFixed(1)} KB · click to change
                      </p>
                    </>
                  ) : (
                    <>
                      <div className="w-12 h-12 rounded-xl border flex items-center justify-center mx-auto mb-3"
                        style={{ background: 'rgba(61,126,255,0.1)', borderColor: 'rgba(61,126,255,0.22)' }}>
                        <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
                          <path d="M10 3v10M6 7l4-4 4 4" stroke="#3D7EFF" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                          <path d="M3 14v1a2 2 0 002 2h10a2 2 0 002-2v-1" stroke="#3D7EFF" strokeWidth="1.5" strokeLinecap="round"/>
                        </svg>
                      </div>
                      <p className="font-medium text-white/65 text-sm">Drop your resume here</p>
                      <p className="text-white/25 text-xs mt-1">PDF or TXT · click to browse</p>
                    </>
                  )}
                </div>

                {/* Error */}
                {error && (
                  <div className="rounded-xl px-4 py-3 text-sm mb-5 border"
                    style={{ background: 'rgba(255,87,87,0.08)', borderColor: 'rgba(255,87,87,0.22)', color: 'rgba(255,87,87,0.85)' }}>
                    {error}
                  </div>
                )}

                {/* CTA */}
                <button
                  onClick={handleStart}
                  disabled={loading || !file}
                  className="btn-azure w-full py-3.5 rounded-xl font-semibold text-sm text-white flex items-center justify-center gap-2"
                >
                  {loading ? (
                    <>
                      <div className="w-4 h-4 rounded-full border-2 border-white/20 border-t-white animate-spin" />
                      Analysing resume…
                    </>
                  ) : (
                    <>Start Interview Session <span className="opacity-50">→</span></>
                  )}
                </button>

                {/* Feature list */}
                <div className="divider my-6" />
                <ul className="space-y-3">
                  {FEATURES.map((f) => (
                    <li key={f.text} className="flex items-start gap-3">
                      <span className="text-azure text-xs flex-shrink-0 mt-0.5">{f.icon}</span>
                      <span className="text-white/35 text-xs leading-relaxed">{f.text}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            <p className="text-center text-xs text-white/18 mt-4">
              Your data is processed locally and never stored permanently.
            </p>
          </div>

        </div>
      </div>
    </div>
  );
}
